/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChildComponent: typeof import('./../src/view/child_parent/ChildComponent.vue')['default']
    ChildComponent2: typeof import('./../src/view/parent_child/ChildComponent2.vue')['default']
    Deal_blind: typeof import('./../src/view/deal_blind.vue')['default']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElRow: typeof import('element-plus/es')['ElRow']
    Father: typeof import('./../src/view/inject_provide/father.vue')['default']
    Found: typeof import('./../src/view/found.vue')['default']
    Grandpa: typeof import('./../src/view/inject_provide/grandpa.vue')['default']
    HelloWorld: typeof import('./../src/components/HelloWorld.vue')['default']
    If_for: typeof import('./../src/view/if_for.vue')['default']
    Live: typeof import('./../src/view/live.vue')['default']
    LocalStorage: typeof import('./../src/view/localStorage.vue')['default']
    ParentComponent: typeof import('./../src/view/child_parent/ParentComponent.vue')['default']
    ParentComponent2: typeof import('./../src/view/parent_child/ParentComponent2.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Son: typeof import('./../src/view/inject_provide/son.vue')['default']
    Try: typeof import('./../src/view/try.vue')['default']
    Watch: typeof import('./../src/view/watch.vue')['default']
  }
}
